### ISSUE TITLE
Volume.sh not working

### ISSUE THREAD

**Issue by dimakow** [levimake/xfce4-genmon-panel-scripts#3]
Hi Levimake,

for some reason the volume.sh is not working correctly for me. If used like in this repo, the css is not being rendered correctly. I need to add:

`INFO+="<txtclick></txtclick>"`

to make it work.

Can you confirm that it works for you with current main?

**Comment by levimake** [comment]
Hi, it works without the line

`
INFO+="<txtclick></txtclick>"
`

I think its because of the XFCE version that we're using. I am using v4.18.

Anyway, for backwards compatibility, I have added the line 
`
INFO+="<txtclick></txtclick>"
`

Thanks.

**Comment by levimake** [comment]
Closing the issue as the commit has been made.
[](https://github.com/levimake/xfce4-genmon-panel-scripts/commit/da30e4ae804fbe54b5faa904b8ad68873865c54b)

**Comment by levimake** [comment]
Sorry, I am reverting the commit as its causing errors when I click on the button. The click is enabled only if you have pavucontrol (pulse audio volume control) installed.
